# Generated by Django 5.2.17 on 2026-08-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('short_bio', models.TextField(blank=True, default='')),
                ('birth_year', models.CharField(blank=True, default='', max_length=50)),
                ('death_year', models.CharField(blank=True, default='', max_length=50)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('medium', models.CharField(blank=True, default='', max_length=255)),
                ('dimensions', models.CharField(blank=True, default='', max_length=255)),
                ('museum', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(max_length=1024)),
                ('short_description', models.TextField(blank=True, default='')),
                ('full_description', models.TextField(blank=True, default='')),
                ('source_museum', models.CharField(blank=True, default='', max_length=255)),
                ('full_description_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('license', models.CharField(default='Public Domain / CC0', max_length=100)),
                ('category', models.CharField(default='All Classics', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('audio_title', models.CharField(blank=True, default='', max_length=255)),
                ('audio_composer', models.CharField(blank=True, default='', max_length=255)),
                ('audio_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='catalog.artist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
